ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS operating_hours JSONB DEFAULT '{}';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'en';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'NPR';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS timezone TEXT DEFAULT 'Asia/Kathmandu';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS date_format TEXT DEFAULT 'ad';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS cover_url TEXT;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS vat_number TEXT;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS vat_registered BOOLEAN DEFAULT false;
